import type { IntegrationProviderCatalogItem } from "./integration-types"

export const integrationMockCatalog: IntegrationProviderCatalogItem[] = [
  {
    provider: "shopify",
    displayName: "Shopify",
    authMode: "api_key",
    baseUrl: "https://store.myshopify.com",
    category: "native",
    limitPerWorkspace: 2,
    usageCount: 18420,
    credentials: { mode: "API key + secret", storage: "server-only encrypted" },
    capabilities: ["pedidos", "carrinho", "catálogo"],
    schema: [
      { key: "store_url", label: "Store URL", type: "string", required: true },
      { key: "api_key", label: "API key", type: "password", required: true },
      { key: "webhook_topic", label: "Webhook topic", type: "select", options: [{ label: "Orders/Create", value: "orders/create" }, { label: "Orders/Paid", value: "orders/paid" }] },
    ],
    tools: [
      {
        key: "get_order",
        label: "Buscar pedido",
        description: "Recupera pedido por número ou id externo.",
        supportsJsonParser: true,
        inputSchema: [{ key: "order_id", label: "Order ID", type: "string", required: true }],
        outputSchema: [{ key: "payload", label: "Payload retorno", type: "json" }],
      },
      {
        key: "update_fulfillment",
        label: "Atualizar fulfillment",
        description: "Sincroniza status logístico.",
        inputSchema: [{ key: "order_id", label: "Order ID", type: "string", required: true }, { key: "status", label: "Status", type: "select", options: [{ label: "Packed", value: "packed" }, { label: "Shipped", value: "shipped" }] }],
        outputSchema: [{ key: "success", label: "Resultado", type: "boolean" }],
      },
    ],
  },
  {
    provider: "whatsapp",
    displayName: "WhatsApp Cloud",
    authMode: "bearer",
    baseUrl: "https://graph.facebook.com",
    category: "native",
    limitPerWorkspace: 4,
    usageCount: 42110,
    credentials: { mode: "Bearer token", storage: "server-only encrypted" },
    capabilities: ["templates", "envio", "webhooks"],
    schema: [
      { key: "phone_number_id", label: "Phone number ID", type: "string", required: true },
      { key: "access_token", label: "Access token", type: "password", required: true },
      { key: "verify_token", label: "Verify token", type: "password", required: true },
    ],
    tools: [
      {
        key: "send_template",
        label: "Enviar template",
        description: "Dispara template aprovado.",
        supportsJsonParser: true,
        inputSchema: [{ key: "template_name", label: "Template", type: "string", required: true }, { key: "contact_phone", label: "Telefone", type: "string", required: true }],
        outputSchema: [{ key: "message_id", label: "Message ID", type: "string" }],
      },
      {
        key: "mark_as_read",
        label: "Marcar como lida",
        description: "Confirma leitura operacional.",
        inputSchema: [{ key: "message_id", label: "Message ID", type: "string", required: true }],
        outputSchema: [{ key: "success", label: "Resultado", type: "boolean" }],
      },
    ],
  },
  {
    provider: "hubspot",
    displayName: "HubSpot",
    authMode: "oauth2",
    baseUrl: "https://api.hubapi.com",
    category: "native",
    limitPerWorkspace: 1,
    usageCount: 9320,
    credentials: { mode: "OAuth2", storage: "server-only encrypted" },
    capabilities: ["contatos", "deals", "pipeline"],
    schema: [
      { key: "portal_id", label: "Portal ID", type: "string", required: true },
      { key: "scopes", label: "Scopes", type: "textarea" },
    ],
    tools: [
      {
        key: "upsert_contact",
        label: "Upsert contato",
        description: "Cria ou atualiza contato por email/telefone.",
        supportsJsonParser: true,
        inputSchema: [{ key: "email", label: "Email", type: "string" }, { key: "phone", label: "Telefone", type: "string" }],
        outputSchema: [{ key: "contact_id", label: "Contact ID", type: "string" }],
      },
    ],
  },
  {
    provider: "erp",
    displayName: "ERP Comercial",
    authMode: "basic",
    baseUrl: "https://erp.mock.local",
    category: "custom",
    limitPerWorkspace: 3,
    usageCount: 6810,
    credentials: { mode: "Basic auth", storage: "server-only encrypted" },
    capabilities: ["estoque", "pedido", "preço"],
    schema: [
      { key: "username", label: "Usuário", type: "string", required: true },
      { key: "password", label: "Senha", type: "password", required: true },
      { key: "environment", label: "Ambiente", type: "select", options: [{ label: "Produção", value: "prod" }, { label: "Sandbox", value: "sandbox" }] },
    ],
    tools: [
      {
        key: "sync_inventory",
        label: "Sincronizar estoque",
        description: "Atualiza saldo por SKU.",
        inputSchema: [{ key: "sku", label: "SKU", type: "string", required: true }],
        outputSchema: [{ key: "stock", label: "Saldo", type: "number" }],
      },
    ],
  },
  {
    provider: "frenet",
    displayName: "Frenet",
    authMode: "api_key",
    baseUrl: "https://api.frenet.com.br",
    category: "native",
    limitPerWorkspace: 1,
    usageCount: 2480,
    credentials: { mode: "API key", storage: "server-only encrypted" },
    capabilities: ["tracking", "prazo"],
    schema: [{ key: "token", label: "Token", type: "password", required: true }],
    tools: [
      {
        key: "track_order",
        label: "Rastrear pedido",
        description: "Recupera tracking por código.",
        inputSchema: [{ key: "tracking_code", label: "Código", type: "string", required: true }],
        outputSchema: [{ key: "events", label: "Eventos", type: "json" }],
      },
    ],
  },
  {
    provider: "melhor_envio",
    displayName: "Melhor Envio",
    authMode: "oauth2",
    baseUrl: "https://api.melhorenvio.com.br",
    category: "native",
    limitPerWorkspace: 1,
    usageCount: 3510,
    credentials: { mode: "OAuth2", storage: "server-only encrypted" },
    capabilities: ["frete", "etiquetas"],
    schema: [{ key: "client_id", label: "Client ID", type: "string", required: true }],
    tools: [
      {
        key: "generate_label",
        label: "Gerar etiqueta",
        description: "Cria etiqueta logística.",
        supportsJsonParser: true,
        inputSchema: [{ key: "order_id", label: "Order ID", type: "string", required: true }],
        outputSchema: [{ key: "label_url", label: "URL etiqueta", type: "string" }],
      },
    ],
  },
  {
    provider: "crm",
    displayName: "CRM Onda",
    authMode: "service_role",
    baseUrl: "https://crm.mock.local",
    category: "custom",
    limitPerWorkspace: 1,
    usageCount: 12020,
    credentials: { mode: "Service role", storage: "server-only encrypted" },
    capabilities: ["perfil", "segmento", "vip"],
    schema: [{ key: "workspace_scope", label: "Escopo", type: "string", required: true }],
    tools: [
      {
        key: "upsert_profile",
        label: "Atualizar perfil",
        description: "Sincroniza perfil e segmentação.",
        inputSchema: [{ key: "contact_id", label: "Contact ID", type: "string", required: true }],
        outputSchema: [{ key: "profile", label: "Perfil", type: "json" }],
      },
    ],
  },
  {
    provider: "zendesk",
    displayName: "Zendesk",
    authMode: "token",
    baseUrl: "https://company.zendesk.com",
    category: "native",
    limitPerWorkspace: 1,
    usageCount: 1940,
    credentials: { mode: "API token", storage: "server-only encrypted" },
    capabilities: ["tickets", "handoff"],
    schema: [{ key: "subdomain", label: "Subdomínio", type: "string", required: true }],
    tools: [
      {
        key: "create_ticket",
        label: "Criar ticket",
        description: "Abre ticket para handoff humano.",
        inputSchema: [{ key: "subject", label: "Assunto", type: "string", required: true }, { key: "body", label: "Descrição", type: "textarea", required: true }],
        outputSchema: [{ key: "ticket_id", label: "Ticket ID", type: "string" }],
      },
    ],
  },
  {
    provider: "n8n",
    displayName: "n8n Ops",
    authMode: "bearer",
    baseUrl: "https://n8n.meusuper.app",
    category: "native",
    limitPerWorkspace: 2,
    usageCount: 6120,
    credentials: { mode: "Bearer token", storage: "server-only encrypted" },
    capabilities: ["webhooks", "workflows", "agents"],
    schema: [
      { key: "base_url", label: "Base URL", type: "string", required: true },
      { key: "api_key", label: "API key", type: "password", required: true },
    ],
    tools: [
      {
        key: "run_workflow",
        label: "Executar workflow",
        description: "Dispara um workflow operacional por nome ou id.",
        supportsJsonParser: true,
        inputSchema: [{ key: "workflow_id", label: "Workflow ID", type: "string", required: true }],
        outputSchema: [{ key: "execution_id", label: "Execution ID", type: "string" }],
      },
      {
        key: "inspect_execution",
        label: "Inspecionar execução",
        description: "Consulta execução recente e surface de erro.",
        inputSchema: [{ key: "execution_id", label: "Execution ID", type: "string", required: true }],
        outputSchema: [{ key: "payload", label: "Payload", type: "json" }],
      },
    ],
  },
  {
    provider: "supabase",
    displayName: "Supabase Knowledge",
    authMode: "service_role",
    baseUrl: "https://project.supabase.co",
    category: "native",
    limitPerWorkspace: 1,
    usageCount: 4380,
    credentials: { mode: "Service role", storage: "server-only encrypted" },
    capabilities: ["postgres", "storage", "vector"],
    schema: [
      { key: "project_url", label: "Project URL", type: "string", required: true },
      { key: "service_role", label: "Service role", type: "password", required: true },
    ],
    tools: [
      {
        key: "query_documents",
        label: "Consultar documentos",
        description: "Recupera documentos e chunks para grounding e debug.",
        supportsJsonParser: true,
        inputSchema: [{ key: "document_id", label: "Document ID", type: "string" }],
        outputSchema: [{ key: "rows", label: "Rows", type: "json" }],
      },
    ],
  },
  {
    provider: "openai",
    displayName: "OpenAI Assistants",
    authMode: "bearer",
    baseUrl: "https://api.openai.com",
    category: "native",
    limitPerWorkspace: 2,
    usageCount: 5890,
    credentials: { mode: "Bearer token", storage: "server-only encrypted" },
    capabilities: ["assistants", "responses", "embeddings"],
    schema: [
      { key: "api_key", label: "API key", type: "password", required: true },
      { key: "organization", label: "Organization", type: "string" },
    ],
    tools: [
      {
        key: "run_prompt",
        label: "Executar prompt",
        description: "Executa prompt operacional com retorno textual estruturado.",
        supportsJsonParser: true,
        inputSchema: [{ key: "prompt", label: "Prompt", type: "textarea", required: true }],
        outputSchema: [{ key: "response", label: "Response", type: "json" }],
      },
    ],
  },
] as const
